#! /bin/bash
if [ $# -ne 1 ]
then 
	echo 'enter the file name to be decrypted'
	exit 1
fi
if [ ! -e "$1" ]
then 
	echo "file does not exist"
	exit 2
fi
CONCAT="$1: openssl enc'd data with salted password, base64 encoded"
if [ "$(file $1)" != "$CONCAT" ]
then
	echo "file has not been encrypted"
	exit 3
fi
echo "Please enter the passphrase."
read -s PASSPHRASE
# opensll will ask the user for a password by default but i wanted the the question to be different.
openssl aes-256-cbc -base64 -d -k $PASSPHRASE -a -salt -in "$1" 
if [ $? -ne 0 ]
then
	echo "decyption failed."
	exit 4
fi
echo
exit 0