#!/usr/bin/env bash
if [ $# -ne 1 ]
then 
	echo 'enter the file name to be decrypted'
	exit 1
fi
if [ ! -e "$1" ]
then 
	echo "file does not exist"
	exit 2
fi
echo "Please enter the passphrase."
read -s PASSPHRASE
# opensll will ask the user for a password by default but i wanted the the question to be different.
openssl aes-256-cbc -base64 -d -pbkdf2 -in "$1" -kfile <(printf "%s" "${PASSPHRASE}")
if [ $? -ne 0 ]
then
	echo "decyption failed."
	exit 3
fi
echo
exit 0