#!/usr/bin/env bash
set -euo pipefail
if [ $# -ne 1 ]
then 
	>&2 echo 'enter the file name to be encripted'
	exit 1
fi
if [ ! -e "$1" ]
then 
	>&2 echo "file does not exist"
	exit 2
fi
if [ -e "$1".enc ]
then
	>&2 echo "file already encrypted"
	exit 3
fi
echo "Please enter the passphrase"
read -s -r PASSPHRASE
# opensll will ask the user for a password by default but i wanted the the question to be different.
openssl aes-256-cbc -base64 -pbkdf2 -in "$1" -out "$1".enc -kfile <(printf "%s" "${PASSPHRASE}") || {
	>&2 echo "encryption failed."
	rm "$1".enc
	exit 4
}

rm "$1"
